name: Deploy Site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: script
      run: |
        ls
        git status
        git remote -v 
        npm install
        pushd themes
        git clone https://github.com/scriptnull/hexo-theme-cactus.git cactus
        popd
        ./package.sh
        git status
        git add docs/
        git add package-lock.json
        git config --global user.email "vishnubharathi04@gmail.com"
        git config --global user.name "Vishnu Bharathi"
        git commit -m "Generated site :sparkles:"
        git push origin master
