name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Hexo Generate
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        ls
        git status
        git remote -v 
        npm install
        pushd themes
        git clone https://github.com/scriptnull/hexo-theme-cactus.git cactus
        popd
        ./package.sh
        git status
        git add docs/
        git add package-lock.json
        git config --global user.email "vishnubharathi04@gmail.com"
        git config --global user.name "Vishnu Bharathi"
        git commit -m "Generated site :sparkles:"
    - name: Push changes
      if: startsWith(github.event.head_commit.message, '[deploy]')
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_PAGES_TOKEN }}
