name: Deploy Site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: script
      run: |
        ls
        git status
        git remote -v 
        npm install
        pushd themes
        git clone https://github.com/scriptnull/hexo-theme-cactus.git cactus
        popd
        ./package.sh
